### ISSUE TITLE
Bug: Gifts are gone when I reopen blind box 

### ISSUE THREAD

**Issue by yfeng2824** [lee920217/PhilosopherStone#25]
**Current:**
1. If I add X gifts in a blind box, navigate to other page and navigate back, the gifts will be gone from this blind box 
2. There's no way for users to add more gifts if the blind box isn't empty
3. The page pops up "1 error" at the bottom left (after I open a blind box)
<img width="1046" alt="Screenshot 2024-01-22 at 1 05 12 PM" src="https://github.com/lee920217/PhilosopherStone/assets/140578792/e1f1d2ac-33b7-4d44-a31e-1126e1b2e4d0">

**Expected:** 
1. Added gifts should be properly displayed in the blind box
2. The page should display # of gifts within the blind box and also a button for users to add more gift
<img width="347" alt="Screenshot 2024-01-22 at 1 09 43 PM" src="https://github.com/lee920217/PhilosopherStone/assets/140578792/88c1bfa9-2d43-47cd-b6c5-f73422052e58">

**Comment by lee920217** [comment]
Now these three bug has been fixed in https://github.com/lee920217/PhilosopherStone/pull/23
