### ISSUE TITLE
[H] Share Gifts via URL

### ISSUE THREAD

**Issue by lee920217** [lee920217/PhilosopherStone#29]
## Background

At present, the sending mode of gifts is still the traditional transaction mode, where users sign a transaction to send Gifts from A to B. However, for one-to-many or airdrop formats, this operation can be somewhat cumbersome.

## Target 
- User could send Gifts via URL or QRCode
- Batch send Gifts

## Process
- Step1:  Create Gifts or Blind Box
- Step2: Send Gifts or Blind Box (Select via URL)
- Step3:  User Sign the transaction
- Step4: Receiver open the URL and collect the Gifts (One URL for One Gift, like Friend Tech Invited Code)

```
1. a sender create a gift (Spore), send the gift to a lock (e.g. secp256k1_blake160) managed by a backend
2. the backend generates a share link and save the context into DB
3. when someone visit the link and provide a CKB address, the backend will send the gift to the address
4. make sure users can view the gift on the PS UI, or at least on CKB explorer
```
@Flouse

**Comment by ashuralyk** [comment]
do you have a simple design in your mind? if so, please write it down.

**Comment by lee920217** [comment]
fixed in https://github.com/lee920217/PhilosopherStone/pull/33
