### ISSUE TITLE
[M] Add a side sliding bar next to Gifts\Blind Box in philosopher-stone

### ISSUE THREAD

**Issue by Dawn-githup** [lee920217/PhilosopherStone#44]
<img width="540" alt="image" src="https://github.com/lee920217/PhilosopherStone/assets/77844990/051d1f95-6d34-4a0f-b7e7-1645de0aaebb">

**Comment by lee920217** [comment]
close it and merge to https://github.com/lee920217/PhilosopherStone/issues/45
